server:
  port: 8601
spring:
  application:
    name: ccip-consumer-consul
  cloud:
    consul:
      host: localhost
      port: 8500
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
