server:
  port: 9004
eureka:
  client: # 客户端进行Eureka注册的配置
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka1:8761/eureka,http://admin:admin@eureka2:8762/eureka,http://admin:admin@eureka3:8763/eureka
