server:
  port: 9011

mybatis-plus:
  mapper-locations: classpath*:com/varian/ccip/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  application:
    name: ccip-patient
  datasource:
    url: jdbc:mysql://localhost:3306/ccip_patient?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.com.varian.ccip: debug
  path: logs/
  file: ccip-patient.log

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:admin@eureka1:8761/eureka,http://admin:admin@eureka2:8762/eureka,http://admin:admin@eureka3:8763/eureka
  instance:
    instance-id: ccip-patient
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒

info:
  app.name: ccip-patient
  company.name: varian
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
